### ISSUE TITLE
switch playmode int java.lang.Integer.intValue()

### ISSUE THREAD

**Issue by tolgatasci** [jrfeng/snow#16]
public LiveData<Integer> getPlayModeDrawable() {
			if (!mInitialized) {
				throw new IllegalStateException("NavigationViewModel not init yet.");
			}

			return Transformations.map(mPlayerViewModel.getPlayMode(), playMode -> {
				switch (playMode) {
					case PLAYLIST_LOOP:
						return R.drawable.ic_play_mode_playlist_loop;
					case LOOP:
						return R.drawable.ic_play_mode_loop;
					case SHUFFLE:
						return R.drawable.ic_play_mode_shuffle;
				}

				return R.drawable.ic_play_mode_playlist_loop;
			});
		}

add my modelview function  and call xml file

	 <ImageButton
								android:id="@+id/switchmode"
								android:layout_width="wrap_content"
								android:layout_height="wrap_content"
								android:onClick="@{() -> modelim.switchPlayMode()}"
								android:layout_weight="1"
								android:src="@{modelim.getPlayModeDrawable}"
							   />

ERROR LOG

	  java.lang.RuntimeException: Failed to call observer method
			at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
			at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
			at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
			at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
			at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
			at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
			at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
			at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
			at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
			at androidx.fragment.app.Fragment.performStart(Fragment.java:2735)
			at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
			at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
			at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
			at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
			at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
			at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
			at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
			at androidx.fragment.app.Fragment.performStart(Fragment.java:2739)
			at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:365)
			at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1194)
			at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
			at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
			at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
			at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
			at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2583)
			at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:258)
			at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:550)
			at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
			at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
			at android.app.Activity.performStart(Activity.java:7923)
			at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3332)
			at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
			at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
			at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
			at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
			at android.os.Handler.dispatchMessage(Handler.java:107)
			at android.os.Looper.loop(Looper.java:224)
			at android.app.ActivityThread.main(ActivityThread.java:7562)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
		 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
			at com.mm.musicmode.databinding.FragmentHomeBindingImpl.executeBindings(FragmentHomeBindingImpl.java:408)
			at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:473)
			at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:445)
	2020-12-14 20:22:20.150 23973-23973/com.mm.musicmode E/AndroidRuntime:     at androidx.databinding.ViewDataBinding$OnStartListener.onStart(ViewDataBinding.java:1687)
			at java.lang.reflect.Method.invoke(Native Method)
			at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
				... 41 more

**Comment by tolgatasci** [comment]
i fixed thank you

binding.setModelim(homeViewModel);
