### ISSUE TITLE
在onRetrieveMusicItemUri中请求服务器获取url时，快速切歌会发生异常闪退

### ISSUE THREAD

**Issue by 2697a** [jrfeng/snow#19]
异常：The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with

**Comment by 2697a** [comment]
`override fun onRetrieveMusicItemUri(musicItem: MusicItem, soundQuality: SoundQuality): Uri {
        if (musicItem.uri == musicItem.musicId) {
            val countDownLatch = CountDownLatch(1)
            var url = ""
            val function = {
                StarryPlugin.channel.invokeMethod("GET_SONG_URL", musicItem.musicId, object : MethodChannel.Result {
                    override fun notImplemented() {
                    }

                    override fun error(errorCode: String?, errorMessage: String?, errorDetails: Any?) {
                        //没有获取到，以后走拼接
                        countDownLatch.countDown()
                    }

                    override fun success(result: Any?) {
                        url = result as String
                        countDownLatch.countDown()
                    }

                })
            }
            StarryPlugin.activity.runOnUiThread(function)
            countDownLatch.await()
            return Uri.parse(url)
        } else {
            return Uri.parse(musicItem.uri)
        }
    }`
这是我的实现，我是做flutter对原生不是很熟悉，如果是我写的问题，麻烦帮我指出一下，谢谢啦~
还有，这个snow真的很不错~

**Comment by jrfeng** [comment]
有更详细的异常信息吗？

**Comment by 2697a** [comment]
有的

`2021-03-07 12:59:49.676 14327-14499/com.sixbugs.bujuan E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-2
    Process: com.sixbugs.bujuan, PID: 14327
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.InterruptedException
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
        at snow.player.AbstractPlayer$1.subscribe(AbstractPlayer.java:327)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1024)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1334)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
        at com.sixbugs.starry.MyPlayerService.onRetrieveMusicItemUri(MyPlayerService.kt:44)
        at snow.player.PlayerService$PlayerImp.retrieveMusicItemUri(PlayerService.java:1262)
        at snow.player.AbstractPlayer$1.subscribe(AbstractPlayer.java:325)
        at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39) 
        at io.reactivex.Single.subscribe(Single.java:3666) 
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) `

**Comment by jrfeng** [comment]
嗯嗯，大概了解，是 `CountDownLatch.await()` 方法抛出的异常，这是由于取消异步任务导致的。这是 `onRetrieveMusicItemUri( MusicItem, SoundQuality)`  方法的缺陷，我会修复它的。

**Comment by 2697a** [comment]
恩恩，好的，我本来改成kotlin的协程，快速切歌不会闪退，但是歌曲跟获取到的url不一致

**Comment by jrfeng** [comment]
@2697a `onRetrieveMusicItemUri( MusicItem, SoundQuality)` 方法已被弃用，升级依赖到 `1.0.9`，然后使用它的重载方法代替：[`onRetrieveMusicItemUri(MusicItem musicItem, SoundQuality soundQuality, AsyncResult<Uri> result)`](https://jrfeng.github.io/snow-doc/snow/player/PlayerService.html#onRetrieveMusicItemUri-snow.player.audio.MusicItem-snow.player.SoundQuality-snow.player.util.AsyncResult-)，详情请查看 Wiki：[音质/动态 URL](https://github.com/jrfeng/snow/wiki/%5BZH%5D-3.%E8%87%AA%E5%AE%9A%E4%B9%89-PlayerService#5-%E9%9F%B3%E8%B4%A8%E5%8A%A8%E6%80%81-url)

**Comment by 2697a** [comment]
好的，给力

**Comment by 2697a** [comment]
> @2697a `onRetrieveMusicItemUri( MusicItem, SoundQuality)` 方法已被弃用，升级依赖到 `1.0.9`，然后使用它的重载方法代替：[`onRetrieveMusicItemUri(MusicItem musicItem, SoundQuality soundQuality, AsyncResult<Uri> result)`](https://jrfeng.github.io/snow-doc/snow/player/PlayerService.html#onRetrieveMusicItemUri-snow.player.audio.MusicItem-snow.player.SoundQuality-snow.player.util.AsyncResult-)，详情请查看 Wiki：[音质/动态 URL](https://github.com/jrfeng/snow/wiki/%5BZH%5D-3.%E8%87%AA%E5%AE%9A%E4%B9%89-PlayerService#5-%E9%9F%B3%E8%B4%A8%E5%8A%A8%E6%80%81-url)

你好，我想问个问题，音乐实时播放进度只能通过livedata监听吗？

**Comment by jrfeng** [comment]
不是的，使用 LiveData 只是方便开发，如果不使用 LiveData 的话，实现起来会有点麻烦，因为实时播放进度需要使用多个监听器配合实现。

**Comment by 2697a** [comment]
> 不是的，使用 LiveData 只是方便开发，如果不使用 LiveData 的话，实现起来会有点麻烦，因为实时播放进度需要使用多个监听器配合实现。

能说一下哪几个配合监听吗？我这边好像用不了liveData,麻烦你了

**Comment by jrfeng** [comment]
实现起来挺麻烦的，如果你确实有需求的话，等下我添加个工具类进去，你直接使用就行。

**Comment by 2697a** [comment]
> 实现起来挺麻烦的，如果你确实有需求的话，等下我添加个工具类进去，你直接使用就行。

恩，好的，谢谢啦

**Comment by jrfeng** [comment]
增加了一个工具类：[`LiveProgress`](https://github.com/jrfeng/snow/blob/master/player/src/main/java/snow/player/util/LiveProgress.java)。这个类会在下个版本发布，可以先把源码复制过去用。如果有 BUG 的话欢迎反馈。

**使用方法：**

```java
LiveProgress liveProgress = new LiveProgress(mPlayerViewModel.getPlayerClient(), new LiveProgress.OnUpdateListener() {
        @Override
        public void onUpdate(int progressSec, int durationSec, String textProgress, String textDuration) {
            // 该方法会在实时播放进度更新时调用。实时播放进度每秒更新一次。
            // 参数说明：
            // progressSec ：当前播放进度，单位：秒
            // durationSec ：歌曲的持续时长，单位：秒
            // textProgress：字符串格式的播放进度，格式为：00:00
            // textDuration：字符串格式的歌曲的持续时长，格式为：00:00
        }
});

// 开始监听播放器实时播放进度的更新
liveProgress.subscribe();

...

// 取消监听实时播放进度
liveProgress.unsubscribe();
```

**注意！当不再需要监听播放器的实时播放进度时，必须调用 `unsubscribe()` 方法取消监听，否则可能会造成内存泄漏。**

或者，还可以调用 `subscribe(LifecycleOwner owner)`   开始监听播放器实时播放进度的更新。使用该方法的好处是，会在 Activity 销毁时自动调用 `unsubscribe()` 方法，可以避免由于忘记调用 `unsubscribe()` 方法而导致的内存泄漏。

**Comment by 2697a** [comment]
> 这个 issue 我关闭了，如果有新问题的话再创建一个新的 issue 吧

好的
