### ISSUE TITLE
Fatal Exception: android.app.ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#27]
`Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.gggggg.ggggg/.MyPlayerService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3345)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8040)
       at android.app.Service.startForeground(Service.java:733)
       at snow.player.PlayerService.startForeground(PlayerService.java:45)
       at snow.player.PlayerService.updateNotificationView(PlayerService.java:32)
       at snow.player.PlayerService$3.onPlaying(PlayerService.java:2)
       at snow.player.AbstractPlayer.notifyPlaying(AbstractPlayer.java:4)
       at snow.player.AbstractPlayer.play(AbstractPlayer.java:78)
       at snow.player.AbstractPlayer$7.onSeekComplete(AbstractPlayer.java:42)
       at snow.player.exo.ExoMusicPlayer$1.onPositionDiscontinuity(ExoMusicPlayer.java:19)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$13(ExoPlayerImpl.java:1)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$0$1d3756c78b6d6b7ece141d7c1e9a6465b69ea5798e59ea3803cb705ea4cacb60$1.invoke(ExoPlayerImpl.java:1)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:4)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:4)
       at com.google.android.exoplayer2.util.ListenerSet$$InternalSyntheticLambda$1$4aa6d67c50ced20c53fd0cecd314136314e77eb5e787a34f9137864aa48c8e5a$0.run(ListenerSet.java:4)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:66)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:10)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:9)
       at com.google.android.exoplayer2.ExoPlayerImpl$$InternalSyntheticLambda$1$c21d15d1115b763b806454db59b3e976fd0126920652a5d519869fbd815a1094$0.run$bridge(ExoPlayerImpl.java:9)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)`

MyPlayerService code is

     `public class MyPlayerService extends PlayerService {
      OkHttpDataSource.Factory OkhttpDataSourceFactory;
       @Override
      public void onCreate() {
        super.onCreate();
        SharedPreferences mPrefs = getSharedPreferences("FmRadio2", MODE_PRIVATE);

        //setMaxIDLETime(10);
    }

    @Nullable
    @Override
    public NotificationView onCreateNotificationView() {
        return new MyCustomNotificationView();
    }

    @Nullable
    @Override
    protected AudioManager.OnAudioFocusChangeListener onCreateAudioFocusChangeListener() {
        return new AudioManager.OnAudioFocusChangeListener() {
            @Override
            public void onAudioFocusChange(int focusChange) {
                Log.e("DEBUG--", "Audio Focus Changed: " + focusChange);
            }
        };
    }

    @NonNull
    @Override
    protected MusicPlayer onCreateMusicPlayer(@NonNull Context context, @NonNull MusicItem musicItem, @NonNull Uri uri) {
        String path = uri.getLastPathSegment();
        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .followRedirects(true)
                .followSslRedirects(true)
                .retryOnConnectionFailure(true)
                .connectTimeout(10, TimeUnit.SECONDS)
                .writeTimeout(10, TimeUnit.SECONDS)
                .readTimeout(10, TimeUnit.SECONDS);

        OkHttpClient okHttpClient = builder.build();
        
        OkhttpDataSourceFactory = new OkHttpDataSource.Factory(
                request -> {
                    Request rq = new Request.Builder(request)
                            // Note: must add head: 'user-agent'
                            .addHeader("user-agent", Util.getUserAgent(context, "xxx-xxx"))
                            .build();
                    return okHttpClient.newCall(rq);
                }
        );

        DefaultDataSource.Factory dataSourceFactory = new DefaultDataSource.Factory(this, OkhttpDataSourceFactory);
        ProgressiveMediaSource.Factory mProgressiveMediaSourceFactory = new ProgressiveMediaSource.Factory(dataSourceFactory);
        HlsMediaSource.Factory mHlsMediaSourceFactory = new HlsMediaSource.Factory(dataSourceFactory);

        if (path != null && path.endsWith(".m3u8")) {
            return new ExoMusicPlayer(context, mHlsMediaSourceFactory, uri);
        }else{
            return new ExoMusicPlayer(context, mProgressiveMediaSourceFactory, uri);
        }
    }
}`

Note:  branches vertion 
https://github.com/jrfeng/snow/tree/upgrade-dependencies

**Comment by jrfeng** [comment]
BUG fixed. 

Please update your `PlayerService` configuration on `AndroidManifest.xml`:

```xml
<service 
    ...
    android:foregroundServiceType="mediaPlayback">
    ...
</service>
```

**Comment by webwayscript** [comment]
Like this ?

        <receiver android:name="androidx.media.session.MediaButtonReceiver"
            android:foregroundServiceType="mediaPlayback"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>

**Comment by jrfeng** [comment]
![image](https://user-images.githubusercontent.com/17897996/160769640-2b87e33b-9ddb-4b51-9ecc-18556ab5a17c.png)

**Comment by jrfeng** [comment]
Apps that target Android 12 (API level 31) or higher can't start foreground services while running in the background. There is no good solution unless the service is always running in the foreground(even if the player has paused).

**Comment by jrfeng** [comment]
BUG fixed, service is always running in the foreground, even if the player has paused.

**Comment by webwayscript** [comment]
thank you now its fixed
