### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#29]
I have this in firebase crash list . this one is your library problem or ourside problem?

      Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 45, Size: 24
       at java.util.ArrayList.get(ArrayList.java:437)
       at snow.player.playlist.Playlist.get(Playlist.java:2)
       at snow.player.AbstractPlayer.playPause(AbstractPlayer.java:2)
       at snow.player.Player__ChannelHelper$Dispatcher.dispatch(Player__ChannelHelper.java:86)
       at channel.helper.DispatcherUtil$1.dispatch(DispatcherUtil.java:19)
       at channel.helper.pipe.CustomActionPipe.dispatch(CustomActionPipe.java:3)
       at snow.player.PlayerService.onCustomAction(PlayerService.java:3)
       at snow.player.PlayerService$MediaSessionCallback.onCustomAction(PlayerService.java:2)
       at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onCustomAction(MediaSessionCompat.java:257)
       at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1635)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:225)
       at android.app.ActivityThread.main(ActivityThread.java:7563)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by jrfeng** [comment]
Sorry, there is too little information. Can you provide more information? I can't find the bug that caused the crash.

**Comment by jrfeng** [comment]
Maybe you used the wrong `position` value to call the `playPause(int position)` method. Maybe you should check your code. I optimized the relevant code, if the wrong `position` value is used, will cause a player error but not crash.
