### ISSUE TITLE
忽略音频焦点会闪退，闪退后无法播放音频，需要重新启用音频焦点才行

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#32]
java.lang.SecurityException: listen
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2441)
        at android.os.Parcel.createException(Parcel.java:2425)
        at android.os.Parcel.readException(Parcel.java:2408)
        at android.os.Parcel.readException(Parcel.java:2350)
        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
        at android.telephony.TelephonyRegistryManager.listenFromListener(TelephonyRegistryManager.java:250)
        at android.telephony.TelephonyManager.listen(TelephonyManager.java:6064)
        at snow.player.helper.PhoneCallStateHelper.registerCallStateListener(PhoneCallStateHelper.java:65)
        at snow.player.AbstractPlayer.requestAudioFocusFailed(AbstractPlayer.java:1413)
        at snow.player.AbstractPlayer.notifyIgnoreAudioFocusChanged(AbstractPlayer.java:1405)
        at snow.player.PlayerService.setIgnoreAudioFocus(PlayerService.java:667)
        at snow.player.PlayerManager__ChannelHelper$Dispatcher.dispatch(PlayerManager__ChannelHelper.java:130)
        at channel.helper.DispatcherUtil$1.dispatch(DispatcherUtil.java:15)
        at channel.helper.pipe.CustomActionPipe.dispatch(CustomActionPipe.java:57)
        at snow.player.PlayerService.onCustomAction(PlayerService.java:1331)
        at snow.player.PlayerService$MediaSessionCallback.onCustomAction(PlayerService.java:1497)
        at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onCustomAction(MediaSessionCompat.java:1814)
        at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8210)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.telephony.TelephonyPermissions.enforceCarrierPrivilege(TelephonyPermissions.java:634)
        at com.android.internal.telephony.TelephonyPermissions.checkReadPhoneState(TelephonyPermissions.java:149)
        at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadPhoneState(TelephonyPermissions.java:94)
        at com.android.server.TelephonyRegistry.checkListenerPermission(TelephonyRegistry.java:3226)
        at com.android.server.TelephonyRegistry.listen(TelephonyRegistry.java:1030)

**Comment by jrfeng** [comment]
收到，我会尽快修复的

**Comment by Janzjoy** [comment]
> 

好的

**Comment by jrfeng** [comment]
BUG 已修复。

**注意！忽略音频焦点后，来电时播放器不会自动暂停播放！如果您想忽略音频焦点，并且在来电时自动暂停播放，则需要在运行时请求 `android.permission.READ_PHONE_STATE` 权限。**

**Comment by jrfeng** [comment]
闪退的问题已经修复了。

之前代码会在忽略音频焦点后，为了在手机来电时自动暂停播放，会监听手机来电状态，而监听手机来电状态需要权限，之前的代码中没有做权限检测，因此导致崩溃。现在已经加上权限检测了，忽略音频焦点后不会再崩溃。但如果还需要在忽略音频焦点后，在手机来电时自动暂停播放，则需要额外在运行时申请 `android.permission.READ_PHONE_STATE` 权限。

**Comment by Janzjoy** [comment]
好了，解决了，谢谢
