### ISSUE TITLE
EqualizerActivity 正在播放音频开启均衡器会闪退

### ISSUE THREAD

**Issue by Janzjoy** [jrfeng/snow#33]
java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:538)
        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:501)
        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:475)
        at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
        at snow.player.ui.equalizer.AndroidAudioEffectManager.attachAudioEffect(AndroidAudioEffectManager.java:72)
        at snow.player.AbstractPlayer.attachAudioEffect(AbstractPlayer.java:1387)
        at snow.player.AbstractPlayer.notifyAudioEffectEnableChanged(AbstractPlayer.java:1374)
        at snow.player.PlayerService.notifyAudioEffectEnableChanged(PlayerService.java:647)
        at snow.player.PlayerService.setAudioEffectEnabled(PlayerService.java:575)
        at snow.player.PlayerManager__ChannelHelper$Dispatcher.dispatch(PlayerManager__ChannelHelper.java:122)
        at channel.helper.DispatcherUtil$1.dispatch(DispatcherUtil.java:15)
        at channel.helper.pipe.CustomActionPipe.dispatch(CustomActionPipe.java:57)
        at snow.player.PlayerService.onCustomAction(PlayerService.java:1331)
        at snow.player.PlayerService$MediaSessionCallback.onCustomAction(PlayerService.java:1497)
        at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onCustomAction(MediaSessionCompat.java:1814)
        at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8210)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by jrfeng** [comment]
没有复现，是最新版源码吗？

**Comment by Janzjoy** [comment]
> 没有复现，是最新版源码吗？
不好意思，用的是1.1的，1.2的可以正常使用，谢谢

**Comment by jrfeng** [comment]
👌好的
