### ISSUE TITLE
qq音乐的播放链接不能播放，用浏览器直接打开是没问题的

### ISSUE THREAD

**Issue by 643063150** [jrfeng/snow#43]
[http://isure.stream.qqmusic.qq.com/C400002ORbbT3FynhJ.m4a?guid=2796982635&vkey=B30C73AF8CF88AF8964FCCE0D2F39348E0FCF5E4AF9208D36FDFC3634389DFEEC2AE4F48B46124491EA05D73BEA6320B26EE596588D9CBF1&uin=&fromtag=120032](url)

错误日志：
2023-03-14 10:20:58.756 20446-20446/com.zpp.mobile.zmusic V/MediaPlayer-JNI: native_setup
2023-03-14 10:20:58.756 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: constructor
2023-03-14 10:20:58.756 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: setListener
2023-03-14 10:20:58.769 20446-20446/com.zpp.mobile.zmusic W/MediaPlayer: Couldn't open "http://isure.stream.qqmusic.qq.com/C400002ORbbT3FynhJ.m4a?guid=2796982635&vkey=B30C73AF8CF88AF8964FCCE0D2F39348E0FCF5E4AF9208D36FDFC3634389DFEEC2AE4F48B46124491EA05D73BEA6320B26EE596588D9CBF1&uin=&fromtag=120032"
    java.io.FileNotFoundException: No content provider: "http://isure.stream.qqmusic.qq.com/C400002ORbbT3FynhJ.m4a?guid=2796982635&vkey=B30C73AF8CF88AF8964FCCE0D2F39348E0FCF5E4AF9208D36FDFC3634389DFEEC2AE4F48B46124491EA05D73BEA6320B26EE596588D9CBF1&uin=&fromtag=120032"
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1680)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1427)
        at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1180)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1152)
        at snow.player.audio.MediaMusicPlayer.prepare(MediaMusicPlayer.java:185)
        at snow.player.AbstractPlayer$2.accept(AbstractPlayer.java:333)
        at snow.player.AbstractPlayer$2.accept(AbstractPlayer.java:322)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2023-03-14 10:20:58.782 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: setVideoSurfaceTexture
2023-03-14 10:20:58.782 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: prepareAsync
2023-03-14 10:20:58.785 20446-21810/com.zpp.mobile.zmusic V/MediaPlayerNative: message received msg=100, ext1=1, ext2=-2147483648
2023-03-14 10:20:58.785 20446-21810/com.zpp.mobile.zmusic E/MediaPlayerNative: error (1, -2147483648)
2023-03-14 10:20:58.807 20446-20446/com.zpp.mobile.zmusic E/MediaPlayer: Error (1,-2147483648)
2023-03-14 10:20:58.807 20446-20446/com.zpp.mobile.zmusic E/MediaMusicPlayer: MediaPlayer Error[what: 1, extra: -2147483648]
2023-03-14 10:20:58.807 20446-20446/com.zpp.mobile.zmusic E/MusicPlayer: errorCode:2
2023-03-14 10:20:58.808 20446-20446/com.zpp.mobile.zmusic V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2023-03-14 10:20:58.808 20446-20446/com.zpp.mobile.zmusic V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2023-03-14 10:20:58.808 20446-20446/com.zpp.mobile.zmusic V/MediaPlayer-JNI: release
2023-03-14 10:20:58.808 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: setListener
2023-03-14 10:20:58.808 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: disconnect
2023-03-14 10:20:58.814 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: destructor
2023-03-14 10:20:58.815 20446-20446/com.zpp.mobile.zmusic V/MediaPlayerNative: disconnect
2023-03-14 10:21:01.236 20446-20446/com.zpp.mobile.zmusic I/ViewRootImpl@7188fca[SongSheetInfo]: MSG_WINDOW_FOCUS_CHANGED 0 1
2023-03-14 10:21:01.236 20446-20446/com.zpp.mobile.zmusic D/InputMethodManager: prepareNavigationBarInfo() DecorView@3349128[SongSheetInfo]
2023-03-14 10:21:01.236 20446-20446/com.zpp.mobile.zmusic D/InputMethodManager: getNavigationBarColor() -855310
2023-03-14 10:21:02.513 20446-20446/com.zpp.mobile.zmusic I/ViewRootImpl@7188fca[SongSheetInfo]: MSG_WINDOW_FOCUS_CHANGED 1 1
2023-03-14 10:21:02.513 20446-20446/com.zpp.mobile.zmusic D/InputMethodManager: prepareNavigationBarInfo() DecorView@3349128[SongSheetInfo]
2023-03-14 10:21:02.513 20446-20446/com.zpp.mobile.zmusic D/InputMethodManager: getNavigationBarColor() -855310

**Comment by 643063150** [comment]
这个是接口的问题，返回了双重“”号 我看了一下午才看出来 太坑了
