### ISSUE TITLE
Need Update Library

### ISSUE THREAD

**Issue by Naguchennai** [jrfeng/snow#49]
Exoplayer changed to Meida3 .. also latest exoplayer only support api 33 only ... we need update this library .

1. When using Api33 Cont Use custum Media Notification bar.. pls check it..
2. 
[r2.19.0](https://github.com/google/ExoPlayer/releases/tag/r2.19.0) [Latest](https://github.com/google/ExoPlayer/releases/latest)
This is the last planned release of the com.google.android.exoplayer2 artifacts. This project is now deprecated. All users should migrate to androidx.media3 (which contains the same ExoPlayer code). See [the migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) for more details, including a script to help with the migration.

thank you

**Comment by jrfeng** [comment]
OK, I'll check it .

**Comment by Naguchennai** [comment]
[r2.19.0](https://github.com/google/ExoPlayer/releases/tag/r2.19.0) [Latest](https://github.com/google/ExoPlayer/releases/latest)
This is the last planned release of the com.google.android.exoplayer2 artifacts. This project is now deprecated. All users should migrate to androidx.media3 (which contains the same ExoPlayer code). See [the migration guide](https://developer.android.com/guide/topics/media/media3/getting-started/migration-guide) for more details, including a script to help with the migration.

**Comment by jrfeng** [comment]
Please check the `migrate-exo` brance.

The `exo` module has been migrated to media3. 

Android 13(API Level 33) has modified the method for customizing media buttons. If your `targetSdkVersion` is greater than or equal to `33`, you also need to use `registerMediaCustomAction(String, CharSequence, int, CustomAction)` register a custom media button in `onInit(Context context)`.

**Example:**

```java
private static class AppNotificationView extends MediaNotificationView {

    @Override
    protected void onInit(Context context) {
        super.onInit(context);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            registerMediaCustomAction(
                    "your_custom_action",
                    "your_custom_action_name",
                    R.mipmap.ic_notif_favorite_false,   // your custom action icon
                    (player, extras) -> {
                        // do something
                    }
            );
        }
        
        // ...
    }
    
    //...
}
```

**Comment by Naguchennai** [comment]
Thank you for updating  ..its working fine 
I have some warining messages its ok? not only this media3 ...even i use old exoplayer also ... its just warming or need take care?

    Handler (android.media.MediaCodec$EventHandler) {c1e5a6d} sending message to a Handler on a dead thread
                                                                                                    java.lang.IllegalStateException: Handler (android.media.MediaCodec$EventHandler) {c1e5a6d} sending message to a Handler on a dead thread
                                                                                                    	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
                                                                                                    	at android.os.Handler.enqueueMessage(Handler.java:786)
                                                                                                    	at android.os.Handler.sendMessageAtTime(Handler.java:735)
                                                                                                    	at android.os.Handler.sendMessageDelayed(Handler.java:705)
                                                                                                    	at android.os.Handler.sendMessage(Handler.java:643)
                                                                                                    	at android.media.MediaCodec.postEventFromNative(MediaCodec.java:5222)
      2023-07-27 11:30:52.431  9209-9444  MessageQueue            snow.player.debug                    W  Handler (android.media.MediaCodec$EventHandler) {c1e5a6d} sending message to a Handler on a dead thread
                                                                                                    java.lang.IllegalStateException: Handler (android.media.MediaCodec$EventHandler) {c1e5a6d} sending message to a Handler on a dead thread
                                                                                                    	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
                                                                                                    	at android.os.Handler.enqueueMessage(Handler.java:786)
                                                                                                    	at android.os.Handler.sendMessageAtTime(Handler.java:735)
                                                                                                    	at android.os.Handler.sendMessageDelayed(Handler.java:705)
                                                                                                    	at android.os.Handler.sendMessage(Handler.java:643)
                                                                                                    	at android.media.MediaCodec.postEventFromNative(MediaCodec.java:5222)
     2023-07-27 11:30:52.432  9209-9444  MessageQueue            snow.player.debug                    W  Handler (android.media.MediaCodec$EventHandler) {c1e5a6d} sending message to a Handler on a dead thread
                                                                                                    java.lang.IllegalStateException: Handler (android.media.MediaCodec$EventHandler) {c1e5a6d} sending message to a Handler on a dead thread
                                                                                                    	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
                                                                                                    	at android.os.Handler.enqueueMessage(Handler.java:786)
                                                                                                    	at android.os.Handler.sendMessageAtTime(Handler.java:735)
                                                                                                    	at android.os.Handler.sendMessageDelayed(Handler.java:705)
                                                                                                    	at android.os.Handler.sendMessage(Handler.java:643)
                                                                                                    	at android.media.MediaCodec.postEventFromNative(MediaCodec.java:5222)

**Comment by jrfeng** [comment]
I don't know the reason for this warning, it seems to be caused by MediaCodec. If the player is working properly, perhaps this warning can be ignored.
