### ISSUE TITLE
Android 14 Error: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by RMA-17** [jrfeng/snow#53]
I'm running in my Android 14 Emulator, and got this error when playing Playlist:

```FATAL EXCEPTION: main
                 Process: com.mukhtarz.appquran, PID: 10142
                 java.lang.RuntimeException: Unable to create service com.mukhtarz.appquran.service.player.MyPlayerService: java.lang.SecurityException: com.mukhtarz.appquran: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                     at android.app.ActivityThread.handleCreateService(ActivityThread.java:4663)
                     at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
                     at android.os.Handler.dispatchMessage(Handler.java:106)
                     at android.os.Looper.loopOnce(Looper.java:205)
                     at android.os.Looper.loop(Looper.java:294)
                     at android.app.ActivityThread.main(ActivityThread.java:8176)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                 Caused by: java.lang.SecurityException: com.mukhtarz.appquran: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                     at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                     at android.os.Parcel.createException(Parcel.java:3041)
                     at android.os.Parcel.readException(Parcel.java:3024)
                     at android.os.Parcel.readException(Parcel.java:2966)
                     at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                     at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
                     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
                     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
                     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                     at snow.player.PlayerService.initCustomActionReceiver(PlayerService.java:482)
                     at snow.player.PlayerService.onCreate(PlayerService.java:202)
                     at android.app.ActivityThread.handleCreateService(ActivityThread.java:4650)
                     at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264) 
                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                     at android.os.Looper.loopOnce(Looper.java:205) 
                     at android.os.Looper.loop(Looper.java:294) 
                     at android.app.ActivityThread.main(ActivityThread.java:8176) 
                     at java.lang.reflect.Method.invoke(Native Method) 
                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                 Caused by: android.os.RemoteException: Remote stack trace:
                     at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13908)
                     at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
                     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
                     at android.os.Binder.execTransactInternal(Binder.java:1339)
                     at android.os.Binder.execTransact(Binder.java:1275)
```

I have followed the process from wiki from the beginning.

I have no errors when I tried on Android 13.

**Comment by jrfeng** [comment]
:ok_hand: OK, I'll fix it

**Comment by jrfeng** [comment]
Need to request a new permission on Android 14:

```xml
<uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK" />
```

**Comment by RMA-17** [comment]
Thanks for the fix, I hope you will update the release soon
